/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java;

public class App{
    public static class Temp{
        int[] arr = new int [3];
        char ch = 'a';
    
        public Temp(int arr[], char ch){
            for(int i=0; i<arr.length; i++){
                this.arr[i] = arr[i];
            }
    
            this.ch = ch;
        }
    }

    public static Temp slv(char arr[], char direction, int position[]){
        int x = position[0], y = position[1], z = position[2];
        char dir = direction;

        for(int i=0; i<arr.length; i++){
            if(dir == 'N'){
                if(arr[i] == 'f'){
                    y++;
                }else if(arr[i] == 'b'){
                    y--;
                }else if(arr[i] == 'l'){
                    dir = 'W';
                }else if(arr[i] == 'r'){
                    dir = 'E';
                }else if(arr[i] == 'u'){
                    dir = 'U';
                }else if(arr[i] == 'd'){
                    dir = 'D';
                }
            }
            else if(dir == 'S'){
                if(arr[i] == 'f'){
                    y--;
                }else if(arr[i] == 'b'){
                    y++;
                }else if(arr[i] == 'l'){
                    dir = 'E';
                }else if(arr[i] == 'r'){
                    dir = 'W';
                }else if(arr[i] == 'u'){
                    dir = 'U';
                }else if(arr[i] == 'd'){
                    dir = 'D';
                }
            }
            else if(dir == 'W'){
                if(arr[i] == 'f'){
                    x--;
                }else if(arr[i] == 'b'){
                    x++;
                }else if(arr[i] == 'l'){
                    dir = 'S';
                }else if(arr[i] == 'r'){
                    dir = 'N';
                }else if(arr[i] == 'u'){
                    dir = 'U';
                }else if(arr[i] == 'd'){
                    dir = 'D';
                }
            }
            else if(dir == 'E'){
                if(arr[i] == 'f'){
                    x++;
                }else if(arr[i] == 'b'){
                    x--;
                }else if(arr[i] == 'l'){
                    dir = 'N';
                }else if(arr[i] == 'r'){
                    dir = 'S';
                }else if(arr[i] == 'u'){
                    dir = 'U';
                }else if(arr[i] == 'd'){
                    dir = 'D';
                }
            }
            else if(dir == 'U'){
                if(arr[i] == 'f'){
                    z++;
                }else if(arr[i] == 'b'){
                    z--;
                }else if(arr[i] == 'l'){
                    dir = 'W';
                }else if(arr[i] == 'r'){
                    dir = 'E';
                }else if(arr[i] == 'u'){
                    dir = 'U';
                }else if(arr[i] == 'd'){
                    dir = 'D';
                }
            }
            else if(dir == 'D'){
                if(arr[i] == 'f'){
                    z--;
                }else if(arr[i] == 'b'){
                    z++;
                }else if(arr[i] == 'l'){
                    dir = 'W';
                }else if(arr[i] == 'r'){
                    dir = 'E';
                }else if(arr[i] == 'u'){
                    dir = 'U';
                }else if(arr[i] == 'd'){
                    dir = 'D';
                }
            }
        }
        Temp temp = new Temp(new int[] {x,y,z}, dir); 
        return temp;
    }

    public static void main(String args[]){
        char arr[] = {'f', 'r', 'u', 'b', 'l'};
        char direction = 'N';
        int position[] = {0,0,0};

        Temp temp = slv(arr, direction, position);
        System.out.println(temp.ch);
        for(int i=0; i<temp.arr.length; i++){
            System.out.print(temp.arr[i]+" ");
        }
        
    }
}
    

   


