/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        char arr[] = {'f', 'r', 'u', 'b', 'l'};
        int position[] = {0,0,0};
        assertNotNull(classUnderTest.slv(arr, 'N',position), "N 0,1,-1");
    }
}
